### ISSUE TITLE
When plugin is enabled, cannot create new printer profiles

### ISSUE THREAD

**Issue by devslashlol** [Mrnt/OctoPrint-FlashForge#52]
V0.2.3 - when the plugin is installed, i cannot create a new printer profile. I had to remove the plugin (I did not try disabling it) to create a new profile, then re-add the plugin

**Comment by Mrnt** [comment]
This should be addressed in release v0.2.4 which is now up.

**Comment by Mrnt** [comment]
Closing. Please reopen if this continues to be an issue.
