### ISSUE TITLE
Filament Ejects After Print Finishes (Finder 2)

### ISSUE THREAD

**Issue by martonbaksa** [Mrnt/OctoPrint-FlashForge#76]
Hi!
I'm using octoprint 1.6.1 and the latest version of your plugin as of Jun 09, 2021. I've been printing with octoprint and it seems as though whenever there's a completed print, it ejects the filament. I don't see this as part of the .gx file itself, so I'm wondering if there's some setting or something causing the machine to eject at the end of every print?
Best,
Em

**Comment by Mrnt** [comment]
Sorry for the long delay in responding. There should not be anything in the plugin that causes the filament to eject. 

If you are sure the slicer did not add anything at the end of the GX file, check to see if you added anything to the after printer settings in OctoPrint. Either way you should be able to see the command that causes the behavior being passed to the printer if you watch the Teminal tab in OctoPrint at the end of the print.
