### ISSUE TITLE
Creatorbot 3D Pro Series II

### ISSUE THREAD

**Issue by TheChief0117** [Mrnt/OctoPrint-FlashForge#82]
I can't connect nor detect my creatorbot 3d Pro Series II. I've got it all USB wired into my laptop, i installed the plugin and followed the guide step by step for octoprint yet it won't connect what so ever...

**Comment by Mrnt** [comment]
This plugin is for printers made by FlashForge. I believe the Creatorbot 3D Pro is made by 3D PrinterWorks so it will not work with this plugin.
